apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopify-hanteo-integration
  namespace: production
  labels:
    app: shopify-hanteo-integration
    environment: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shopify-hanteo-integration
  template:
    metadata:
      labels:
        app: shopify-hanteo-integration
        version: "1.0.0"
    spec:
      serviceAccountName: shopify-hanteo-integration
      containers:
      - name: app
        image: ghcr.io/your-org/shopify-hanteo-integration:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        - name: TZ
          value: "Asia/Seoul"
        envFrom:
        - secretRef:
            name: shopify-hanteo-secrets
        - configMapRef:
            name: shopify-hanteo-config
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        volumeMounts:
        - name: logs
          mountPath: /app/logs
      volumes:
      - name: logs
        emptyDir: {}
      imagePullSecrets:
      - name: ghcr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: shopify-hanteo-integration
  namespace: production
  labels:
    app: shopify-hanteo-integration
spec:
  type: ClusterIP
  selector:
    app: shopify-hanteo-integration
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shopify-hanteo-integration
  namespace: production
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rate-limit: "100"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  tls:
  - hosts:
    - api.hallyusuperstore.com
    secretName: shopify-hanteo-tls
  rules:
  - host: api.hallyusuperstore.com
    http:
      paths:
      - path: /webhooks
        pathType: Prefix
        backend:
          service:
            name: shopify-hanteo-integration
            port:
              number: 80
      - path: /health
        pathType: Exact
        backend:
          service:
            name: shopify-hanteo-integration
            port:
              number: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: shopify-hanteo-config
  namespace: production
data:
  HANTEO_ENV: "production"
  HANTEO_FAMILY_CODE: "HF0082CST001"
  HANTEO_BRANCH_CODE: "001"
  SHOPIFY_STORE_DOMAIN: "hallyusuperstore.myshopify.com"
  SHOPIFY_API_VERSION: "2025-04"
  LOG_LEVEL: "info"
---
apiVersion: v1
kind: Secret
metadata:
  name: shopify-hanteo-secrets
  namespace: production
type: Opaque
stringData:
  SHOPIFY_ADMIN_ACCESS_TOKEN: "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"
  HANTEO_TEST_CLIENT_KEY: "NDY2OTg1NDk1Oml+VUhdVyYlYltWZQ=="
  HANTEO_PROD_CLIENT_KEY: "MTY3NjEwMzcxNzphUmMzckdxdlo/M0A="
  SHOPIFY_WEBHOOK_SECRET: "your-webhook-secret"
  SYNC_API_KEY: "your-sync-api-key"
  REDIS_URL: "redis://redis-service:6379"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: shopify-hanteo-integration
  namespace: production
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: shopify-hanteo-integration
  namespace: production
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: shopify-hanteo-integration
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: shopify-hanteo-integration
  namespace: production
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: shopify-hanteo-integration
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80